### ISSUE TITLE
Is there any update on this?

### ISSUE THREAD

**Issue by matgrioni** [conllul/conllul.github.io#1]
What is the current status of the conllul project? It seems like the last update was in 2018 and lines up with before UD 2.2. Is there any active work being done on this project or possible in the future, or is it deprecated at this point?

**Comment by habeanf** [comment]
Sadly, there is no active work being done on this project. I was the first author of the CoNLL-UL paper, so I did most of the heavy lifting to get the conllul repositories and docker going. It's also my impression that this project does not receive much attention, since as you can see, you're the first to comment on it in 3 years (including all the language repos in the project).

I'm no longer involved in the NLP community (academic or industry), and none of the associated research labs are interested in taking on the task of maintenance since they have no funding for it.

I would re-run some old scripts to update conllul for newer UD versions, but they'd only work if the UD scheme has not changed since version 2.2, which I doubt.

Sorry :(

**Comment by matgrioni** [comment]
I figured as much about the state of the project, which is a shame since it seems like a nice contribution to the conll space. The scripts would have a decent chance of running on version 2.7 of UD (the latest), but I actually don't need the data specifically, I was more looking at if this file format should be supported natively for a general CoNLL parsing library.

Seems like the answer is no (at least not soon), which ends up making life a bit easier for me. 😃 

Thanks for the info.
